### ISSUE TITLE
How install "getconf" on CentOS 7 64ARM?

### ISSUE THREAD

**Issue by NycuRO** [pmmp/php-build-scripts#10]
I have CentOS 7 and need "getconf" to compile .

Command: "yum install getconf" not work.

One solution? Jenkins is off.

**Comment by dktapps** [comment]
You don't actually need getconf iirc. Try to compile without it.

**Comment by NycuRO** [comment]
Not work. Get stopped.

**Comment by dktapps** [comment]
Comment out https://github.com/pmmp/php-build-scripts/blob/master/compile.sh#L45

**Comment by dktapps** [comment]
nvm, didn't read the title. Are you trying to cross-compile?

**Comment by NycuRO** [comment]
what can i try this?

**Comment by NycuRO** [comment]
I'm using PHP 7.0.6 from: https://dl.bintray.com/pocketmine/PocketMine/ . And server not start..
