### ISSUE TITLE
Exporting LIBRARY_PATH breaks curl ssl configuration

### ISSUE THREAD

**Issue by onek24** [pmmp/php-build-scripts#100]
When building php using the script, this error occurs using the script, but not when configurating curl manually:

> ...
> configure: PKG_CONFIG_LIBDIR will be set to "/ZFS_Storage/Samba/public/php-build-scripts/bin/php7/lib/pkgconfig"
> checking for pkg-config... /usr/bin/pkg-config
> checking for openssl options with pkg-config... found
> configure: pkg-config: SSL_LIBS: "-lssl -lcrypto "
> configure: pkg-config: SSL_LDFLAGS: ""
> configure: pkg-config: SSL_CPPFLAGS: "-I/ZFS_Storage/Samba/public/php-build-scripts/bin/php7/include "
> checking for HMAC_Update in -lcrypto... no
> checking for HMAC_Init_ex in -lcrypto... no
> checking OpenSSL linking with -ldl... no
> checking OpenSSL linking with -ldl and -lpthread... **no**
> configure: OPT_SSL: /ZFS_Storage/Samba/public/php-build-scripts/bin/php7
> configure: OPENSSL_ENABLED: 
> configure: error: --with-ssl was given but OpenSSL could not be detected
> ...

This can be fixed by removing Line 336 from the script:
`#export LIBRARY_PATH="$DIR/bin/php7/lib:$LIBRARY_PATH"`

Afterwards, all libraries can be found and SSL_LDFLAGS is set correctly and curl completely builds. 

> ...
> configure: PKG_CONFIG_LIBDIR will be set to "/ZFS_Storage/Samba/public/php-build-scripts/bin/php7/lib/pkgconfig"
> checking for pkg-config... /usr/bin/pkg-config
> checking for openssl options with pkg-config... found
> configure: pkg-config: SSL_LIBS: "-lssl -lcrypto "
> configure: pkg-config: SSL_LDFLAGS: "-L/ZFS_Storage/Samba/public/php-build-scripts/bin/php7/lib "
> configure: pkg-config: SSL_CPPFLAGS: "-I/ZFS_Storage/Samba/public/php-build-scripts/bin/php7/include "
> checking for HMAC_Update in -lcrypto... no
> checking for HMAC_Init_ex in -lcrypto... no
> checking OpenSSL linking with -ldl... no
> checking OpenSSL linking with -ldl and -lpthread... **yes**
> checking for SSL_connect in -lssl... yes
> ...

**Comment by dktapps** [comment]
That doesn't make any sense. It builds just fine for everyone else. This has to be related to the script arguments or your environment.

**Comment by onek24** [comment]
I know, i couldn't get it to work otherwise. I'm building with this parameters:
`./build.sh -t linux64 -l -j12 -f x86_64`

**Comment by dktapps** [comment]
Using what OS?

**Comment by onek24** [comment]
Linux. Kernel 5.7.9-arch1-1

**Comment by dktapps** [comment]
> export LIBRARY_PATH="$LIBRARY_PATH"

considering this does nothing whatsoever, I wouldn't say it "fixes" it ...

**Comment by onek24** [comment]
Why is SSL_LDFLAGS empty and linking with -ldl set to no if prepending $DIR/bin/php7/lib: to the path?

**Comment by dktapps** [comment]
I have no idea. But it works correctly on the Azure builds and on every other machine I've seen, so I don't know why yours is different.

**Comment by onek24** [comment]
`php -v`

> PHP 7.3.20 (cli) (built: Jul 25 2020 16:33:02) ( ZTS )


`php -m`

> bcmath
> calendar
> Core
> crypto
> ctype
> curl
> date
> dom
> ds
> filter
> ftp
> gmp
> hash
> igbinary
> json
> leveldb
> libxml
> mbstring
> mysqli
> mysqlnd
> openssl
> pcntl
> pcre
> PDO
> pdo_mysql
> pdo_sqlite
> Phar
> posix
> pthreads
> recursionguard
> Reflection
> shmop
> SimpleXML
> sockets
> SPL
> sqlite3
> standard
> tokenizer
> xml
> xmlreader
> xmlwriter
> yaml
> Zend OPcache
> zip
> zlib

Looks good so far... strange tho

**Comment by onek24** [comment]
I build PMMP master (dev) with chunkutils2 and this php and it works so far. I'll close this issue since this might be related to my local environment.

**Comment by dktapps** [comment]
I'd rather this remain open until we get to the bottom of it.

**Comment by onek24** [comment]
A user in discord wrote, that he had the same issue on Arch

**Comment by onek24** [comment]
install_data/curl/config.log:

[config.log](https://github.com/pmmp/php-build-scripts/files/4976181/config.log)

**Comment by onek24** [comment]
install_data/curl/config.log:
(with export=LD_LIBRARY_PATH="$DIR/bin/php7/lib:$LD_LIBRARY_PATH" added)

[config.log](https://github.com/pmmp/php-build-scripts/files/4976194/config.log)

**Comment by onek24** [comment]
New script curl config.log:
[config.log](https://github.com/pmmp/php-build-scripts/files/4976260/config.log)

New script curl config.log with export LD_LIBRARY_PATH:
[config.log](https://github.com/pmmp/php-build-scripts/files/4976266/config.log)

**Comment by onek24** [comment]
pkgconfig containing:
- libcrypto.pc
- libssl.pc
- openssl.pc

[pkgconfig.zip](https://github.com/pmmp/php-build-scripts/files/4976296/pkgconfig.zip)

**Comment by dktapps** [comment]
There's a behavioural difference between `pkg-config` and `pkgconf` which causes this issue. I'm not entirely sure why this is a problem, but I'm getting there.

**Comment by dktapps** [comment]
please try aaca17ff43d4b1920cdbbc89a2af3e009b0e0005

**Comment by dktapps** [comment]
The above commit fixes the issue on my machine, so I'm going to close this.

**Comment by onek24** [comment]
Fix working on my machine aswell.
