### ISSUE TITLE
gzip: stdin: unexpected end of file

### ISSUE THREAD

**Issue by Endermanbugzjfc** [pmmp/php-build-scripts#104]
### It created an empty bin/php7 and an install_data folder which contains most of the downloaded stuff.
![image](https://user-images.githubusercontent.com/53002741/91736723-b29c2280-ebe0-11ea-9f07-c7507d612a8d.png)
![image](https://user-images.githubusercontent.com/53002741/91736903-f727be00-ebe0-11ea-9a8b-33c4f8e332e9.png)

# install.log
```log
Mon Aug 31 23:06:38 HKT 2020
Linux CCY-E-NB 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
make is /usr/bin/make

autoconf is /usr/bin/autoconf
automake is /usr/bin/automake
m4 is /usr/bin/m4
getconf is /usr/bin/getconf
gzip is /usr/bin/gzip
bzip2 is /usr/bin/bzip2
bison is /usr/bin/bison
g++ is /usr/bin/g++
git is /usr/bin/git
cmake is /usr/bin/cmake
pkg-config is /usr/bin/pkg-config
wget is /usr/bin/wget
libtool is /usr/bin/libtool
wget is /usr/bin/wget
gcc is /usr/bin/gcc
2020-08-31 23:10:19 URL:https://codeload.github.com/php/php-src/tar.gz/php-7.3.21 [11964422] -> "-" [1]

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

# Environment
**Operating system:** Linux Ubuntu 20.04 LTS running on Windows Subsystem for Linux 2 
*(I was going to build the Pocketmine-MP API 4 binary and upload it to my hosting service)*

**Comment by dktapps** [comment]
Blame your internet. This isn't a php-build-scripts problem.
