### ISSUE TITLE
Compilation is not completing

### ISSUE THREAD

**Issue by Govdim** [pmmp/php-build-scripts#109]
At the last stage of PHP compilation, the process is interrupted with the following error:

Makefile:1154: recipe for target 'ext/morton/morton.lo' failed
make: *** [ext/morton/morton.lo] Error 1

branch: master
OS: Ubuntu 18.04

**Comment by dktapps** [comment]
Provide the whole log file.

**Comment by Govdim** [comment]
[install.log](https://github.com/pmmp/php-build-scripts/files/5460948/install.log)

**Comment by dktapps** [comment]
The hardware specifications of the CPU are relevant here, also which flags you passed to `compile.sh`.

**Comment by Govdim** [comment]
Without flags, the result is the same

**Comment by Encritary** [comment]
try passing ``-t linux64``

**Comment by dktapps** [comment]
That shouldn't make any difference.

**Comment by Govdim** [comment]
Does it matter that Linux was launched in the "VirtualBox" program?

**Comment by SOF3** [comment]
As long as your host is using a "normal" architecture (like amd64), virtual machines shall not affect anything.

**Comment by dktapps** [comment]
Yes, it can matter. I experienced this issue in virtualbox, but only when AVX2 was enabled.

**Comment by dktapps** [comment]
Please provide the content of `/proc/cpuinfo` from inside your VM.

**Comment by Govdim** [comment]
[cpuinfo.txt](https://github.com/pmmp/php-build-scripts/files/5493903/cpuinfo.txt)

**Comment by dktapps** [comment]
Interesting, I didn't know AVX was supported on Ryzen CPUs.

It looks like this is caused by the same issue I faced (AVX2 is supported on your CPU but not BMI2).

**Comment by Forceflow** [comment]
I've deplyoyed a possible fix in branch: https://github.com/Forceflow/libmorton/tree/avx_bmi_fix

**Comment by Forceflow** [comment]
Dev version now has fix, will push to main soon.
https://github.com/Forceflow/libmorton/tree/develop

**Comment by dktapps** [comment]
Awesome, thanks for your time @Forceflow

**Comment by Forceflow** [comment]
> 
> 
> Awesome, thanks for your time @Forceflow

No problem, good luck with your project

**Comment by dktapps** [comment]
Fixed by bdce80c6c2e64524b6de56772c16096679abfc8f.
