### ISSUE TITLE
Installer don't work

### ISSUE THREAD

**Issue by AR2000AR** [pmmp/php-build-scripts#11]
Hi,
I want to install PoketMine on my raspberry pi 3 B but the scrip don't do anythig.

pi@raspberrypi3:~/PocketMine $ wget https://raw.githubusercontent.com/pmmp/php-build-scripts/master/installer.sh
--2017-02-16 13:38:39--  https://raw.githubusercontent.com/pmmp/php-build-scripts/master/installer.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.60.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.60.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17393 (17K) [text/plain]
Saving to: ‘installer.sh’

installer.sh        100%[=====================>]  16.99K  --.-KB/s   in 0.02s  

2017-02-16 13:38:40 (890 KB/s) - ‘installer.sh’ saved [17393/17393]

pi@raspberrypi3:~/PocketMine $ bash installer.sh 
[!] Couldn't download version automatically from Jenkins server

**Comment by dktapps** [comment]
Jenkins is currently offline.
