### ISSUE TITLE
Development Channel Not Found

### ISSUE THREAD

**Issue by xaoseric** [pmmp/php-build-scripts#111]
When trying to use the development channel, the api returns a ChannelNotFound error.

**Comment by dktapps** [comment]
It doesn't exist.

**Comment by xaoseric** [comment]
The readme file specifies Channel (stable or development) as valid channels. Which channel do I need to get the latest from the master then?

**Comment by dktapps** [comment]
There are no prebuilts for the master branch, because it made it too easy for uninformed people who don't read to run development builds, which are unsafe.
