### ISSUE TITLE
PHP crash "pointer being freed was not allocated"

### ISSUE THREAD

**Issue by MlsDmitry** [pmmp/php-build-scripts#114]
Since it is PHP crash pmmp hadn't created any crash dumps, at least I didn't see them in crashdumps folder.

My telegram: @mlsdDmitry if you need additional information
A little information about os:
Mac OS: 10.14.6
### I built php with php-build-scripts from pmmp repo (latest php version, I remember it is 7.4)
Here is compile log tar gzip archive;  -> https://drive.google.com/file/d/1G6g0aJk_A8weRoHvCAoE5J3KmWvJD-jY/view?usp=sharing
Last Error lines:
```
php(46154,0x70000f1d3000) malloc: *** error for object 0x108d152d0: pointer being freed was not allocated
php(46154,0x70000f1d3000) malloc: *** set a breakpoint in malloc_error_break to debug
```
Debug log from gdb with breakpoint at malloc_error_break
**password: Tz11EgTCxg** log-> https://pastebin.com/QhCi05G1
I don't have much experience in debugging, but EVP_CipherInit_ex were called from libcurl1.4.dylib, so I guess It is curl's problem not PMMP's. Just close this issue if it related to curl
This crash occur like 4 of 5 runs, that's a lot...
Thanks for any help, sorry it topic doesn't relate to pmmp.

**Comment by MlsDmitry** [comment]
Yep, that's worked, at least I don't see crashes in 5 of 5 runs. Thanks for fast help!

**Comment by MlsDmitry** [comment]
Well, I had another crash. However I can't reproduce it again, will provide you additional crash report as soon as possible

**Comment by dktapps** [comment]
I've updated the build script to newer versions, including a new release of OpenSSL.
This is not the first time that OpenSSL has caused these kinds of issues.

**Comment by MlsDmitry** [comment]
ok, I'm going to close it for now. I appreciate your work, but I don't have time on this month to test.
