### ISSUE TITLE
Compilation is not completing

### ISSUE THREAD

**Issue by Govdim** [pmmp/php-build-scripts#117]
Problem in libdeflate
[install.log](https://github.com/pmmp/php-build-scripts/files/5795458/install.log)

branch: master
OS: Ubuntu 20.04 (VirtualBox 6.1)

**Comment by TheNewHEROBRINEX** [comment]
What arguments did you pass to compile.sh?

**Comment by Govdim** [comment]
> What arguments did you pass to compile.sh?

-f -g -s

**Comment by TheNewHEROBRINEX** [comment]
Is there any reason why are you specifically trying to compile the binaries statically? Try without -s

**Comment by dktapps** [comment]
I think libdeflate builds both shared and static targets unconditionally, so that's probably what caused the issue.

**Comment by Govdim** [comment]
Removed -s, it worked
