### ISSUE TITLE
Directory name incorrect(PHP8 branch)

### ISSUE THREAD

**Issue by Blackjack200** [pmmp/php-build-scripts#118]
I think it is time to change PHP8 build in `bin/php8` instead of `bin/php7`, although it is useless.
Sorry but i'm really not good at English if i am talking rudely, i really didn't mean it, please excuse me, thanks!

**Comment by dktapps** [comment]
I knew someone would make a pointless issue like this...

I purposely didn't change it, because it would break the start.sh and similar scripts. I blame @shoghicp for making `bin/php5` to begin with. I won't continue to be a part of this stupidity that breaks our systems every major update.
