### ISSUE TITLE
Invalid option -?c

### ISSUE THREAD

**Issue by Skintrphoenix** [pmmp/php-build-scripts#120]

**Comment by SOF3** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
