### ISSUE TITLE
Build fails on Windows environment if run windows-compile-vs.bat on another drive (not on C drive)

### ISSUE THREAD

**Issue by alvin0319** [pmmp/php-build-scripts#124]
It seems build script isn't working on another drive

[compile.log](https://github.com/pmmp/php-build-scripts/files/7290082/compile.log)

This is the log what I tried to compile on D drive

(I modified script to use more extension, but I don't think this affected on this bug since this worked on C drive anyways)

**Comment by dktapps** [comment]
This log clearly shows you built on C, not D...

**Comment by DaisukeDaisuke** [comment]
> I use google translate and deepl translate.

The move command does not seem to support moving contents between disks.
As a workaround, there seems to be a need to replace the following move commands with the robocopy or xcopy and rmdir commands.

https://github.com/pmmp/php-build-scripts/blob/fab0cbeaae7de58ea78a02c7505719d04a0325a3/windows-compile-vs.bat#L268-L272

> reference
> https://stackoverflow.com/questions/16502283/how-do-i-fix-access-denied-with-the-move-command-in-windows-7/16506856#16506856

**Comment by alvin0319** [comment]
Closing this due to unable to reproduce anymore.
