### ISSUE TITLE
Linux PHP8 pre-built binary extracts to php7 folder

### ISSUE THREAD

**Issue by ZizzyZizzy** [pmmp/php-build-scripts#128]
Minor annoyance only.

tar -tzvf PHP-8.0-Linux-x86_64.tar.gz | more
drwxr-xr-x vsts/docker       0 2021-10-09 09:37 bin/
drwxr-xr-x vsts/docker       0 2021-10-09 09:47 bin/php7/

**Comment by dktapps** [comment]
This is expected and it's not going to change. It would break various things (primarily start.sh) for no real benefit.
