### ISSUE TITLE
Raspberry pi 3b+ arm64

### ISSUE THREAD

**Issue by mmdkvz** [pmmp/php-build-scripts#129]
Hello , how can i download the php for aarch 64 linux ??

**Comment by dktapps** [comment]
We don't provide downloads for aarch64. You need to compile it yourself.

**Comment by BeanGTA** [comment]
> Hello , how can i download the php for aarch 64 linux ??

https://github.com/BeanGTA/File-BIN-PHP8.0-For-Pocketmine-Android-And-Raspberry-on-Linux

**Comment by SOF3** [comment]
Please do not share random binaries of untrusted sources here.
