### ISSUE TITLE
Compiling with leveldb support

### ISSUE THREAD

**Issue by benwelch** [pmmp/php-build-scripts#13]
So I'm trying to compile the leveldb extension on my raspberry pi pocketmine server so I can use mcpe worlds. It's using php 7. Whenever I try to do this using the compile.sh with the argument -l and the target as rpi (raspberry pi) it does it but when I run my server it says "Couldn't find a working PHP 7 binary, please use the installer." I'm using windows 10.

Apparently this doesn't work with php 7 so how do I downgrade my php binary so that I can do this?

**Comment by dktapps** [comment]
LevelDB currently isn't supported and will not be compiled regardless of whether you specify -l or not.

If you're compiling a binary for use on Win10, you need to cross-compile with target `win` or `win32`.
