### ISSUE TITLE
Please add android-aarch64.

### ISSUE THREAD

**Issue by jiwjung** [pmmp/php-build-scripts#133]
Currently, php bin compilation is not available on android-aarch64 environment.

As PHP 8.0 has become mandatory since the last PMMP version, I have not been able to open my server for the past few months.
I could see that it had not yet been implemented in TODO LIST on the source.

I sincerely ask you to add it as soon as possible.

Thank you for reading :)

**Comment by dktapps** [comment]
Not gonna happen. Stop using your phone to host a server, it's not suitable.

**Comment by BeanGTA** [comment]
> Currently, php bin compilation is not available on android-aarch64 environment.
> 
> As PHP 8.0 has become mandatory since the last PMMP version, I have not been able to open my server for the past few months. I could see that it had not yet been implemented in TODO LIST on the source.
> 
> I sincerely ask you to add it as soon as possible.
> 
> Thank you for reading :)

https://github.com/BeanGTA/File-BIN-PHP8.0-For-Pocketmine-Android-And-Raspberry-on-Linux

**Comment by NTT1906** [comment]
This works [link](https://github.com/DaisukeDaisuke/AndroidPHP) but you shouldn't host your server on Android.

**Comment by SOF3** [comment]
The issue tracker is not a support forum.
