### ISSUE TITLE
cURL fails to build on Mac OSX with cURL 7.82.0

### ISSUE THREAD

**Issue by mclare** [pmmp/php-build-scripts#140]
Build error from install.log OR building cURL indendently:

> configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto -lssl -lcrypto -lz 

This appears to be related to recent changes to cURL build on OSX https://github.com/curl/curl/pull/8247 and cURL build script finding all the versions of openssl available on the mac at that moment.

Reverting the cURL version for OSX compiles from curl-7_82_0 back to curl-7_81_0 (line 6 of complie.sh) allows the compile to complete on OSX.

Clearly an upstream issue, but limited to building on Mac OSX --with-ssl and/or --prefix= . Letting others know its impact on building pocketmine.

**Comment by dktapps** [comment]
Thanks for the analysis. I haven't had time to investigate it yet and I don't have an Mac, so the CI is the best I have.

**Comment by dktapps** [comment]
config.log from an Actions run shows this:
```
dyld: Library not loaded: libz.so.1.2.12
  Referenced from: /Users/runner/work/php-build-scripts/php-build-scripts/install_data/subdir/curl/./conftest
  Reason: image not found
./configure: line 2476: 55412 Abort trap: 6           ./conftest$ac_exeext
configure:33572: $? = 134
```
It would appear this is something borked in cURL which is interacting in a weird way with the rpath set by the script.

**Comment by dktapps** [comment]
Frankly I fail to understand what the problem is here. To the best of my understanding https://github.com/pmmp/php-build-scripts/commit/94bd8410646e39857653a032f021668da47f562d should have fixed the problem, but it didn't.

**Comment by dktapps** [comment]
It appears that zlib 1.2.12 is actually the root cause of this problem. Rolling back to 1.2.11 resolves the issue.

Similar issue: https://github.com/madler/zlib/issues/615
