### ISSUE TITLE
stop from compiling php for no reason 

### ISSUE THREAD

**Issue by TukangM** [pmmp/php-build-scripts#148]
```
sayaaep@sayaaep-Ideapad-Z460:~/php compile pmmp$ ./compile.sh -t android-aarch64 -x -f
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependencies
[opt] Set target to android-aarch64
[opt] Doing cross-compile
[opt] Enabling abusive optimizations...
[INFO] Cross-compiling for Android ARMv8 (aarch64)
[warning] OPcache cannot be used on static builds; this may have a negative effect on performance
[warning] Xdebug cannot be built in static mode
[PHP] downloading 8.0.22... done!
[zlib] downloading 1.2.11... checking... compiling... installing...sayaaep@sayaaep-Ideapad-Z460:~/php compile pmmp$ sudo ./compile.sh -t android-aarch64 -x -f
```
i compile aarch64-musl-gcc https://github.com/richfelker/musl-cross-make on x86_64 machine and run compile.sh zlib stop or exiting

running on linux mint 21 based ubuntu jammy jellyfish

**Comment by dktapps** [comment]
Check the install.log file, it will have more information.

**Comment by SayaAEP** [comment]
[install.log](https://github.com/pmmp/php-build-scripts/files/9733323/install.log)
here

**Comment by DaisukeDaisuke** [comment]
The build script probably does not support directory names containing spaces.
Could you please rename the `php compile pmmp` and remove the spaces and try to build again?
> example
> `php compile pmmp` => `php_compile_pmmp`

**Comment by SayaAEP** [comment]
ahh yess i rename to spaced name



> The build script probably does not support directory names containing spaces. Could you please rename the `php compile pmmp` and remove the spaces and try to build again?
> 
> > `php compile pmmp` => `php_compile_pmmp`

**Comment by SayaAEP** [comment]
```
[zlib] downloading 1.2.11... checking... compiling... installing... done!
```
thank. if there is a problem with compile.sh i will come here
