### ISSUE TITLE
compiling with openssl

### ISSUE THREAD

**Issue by SuperPuperSteve** [pmmp/php-build-scripts#15]
how to compile PHP with openssl?

**Comment by markkrueg** [comment]
It would indeed be good if this script included openssl by default; as it will soon become mandatory.

**Comment by TheDiamondYT1** [comment]
Its not needed anymore, as per https://github.com/pmmp/PocketMine-MP/commit/8a28021b4468433a21fab392ce22c04957ed324b

**Comment by TheDiamondYT1** [comment]
However the zip exstension *is* needed.

**Comment by dktapps** [comment]
Zip is already included... you just used a bin which wasn't provided by PocketMine.

**Comment by TheDiamondYT1** [comment]
Oh, okay. My problem is i dont havw access to linux right now so i cant compile a binary for myself

**Comment by dktapps** [comment]
The OpenSSL extension will be required in the near future for authentication purposes, as will the GMP extension.

**Comment by Pizzahaet** [comment]
@dktapps any way I can compile it now with openssl? I just really need openssl for Xbox Auth

**Comment by dktapps** [comment]
OpenSSL isn't going to make Xbox auth work just like magic.

**Comment by Pizzahaet** [comment]
yes i know

**Comment by TheDiamondYT1** [comment]
We dont need it. 1.2 will force xbox auth

**Comment by KnownUnown** [comment]
@TheDiamondYT1 because nobody will patch that out ;)

**Comment by TheDiamondYT1** [comment]
@KnownUnown I'll be making a mod to bypass ASAP

**Comment by dktapps** [comment]
https://github.com/pmmp/php-build-scripts/tree/openssl now has OpenSSL included, tested on android-aarch64, linux & windows. I can't test Mac very well due to my VM being a pain in the ass, anyone want to help?

**Comment by TheNewHEROBRINEX** [comment]
I tested on mac and composer fails to download because mac hasn't wget https://github.com/pmmp/php-build-scripts/blob/openssl/compile.sh#L932

**Comment by dktapps** [comment]
@TheNewHEROBRINEX Thanks a lot! I pushed a fix for that, could you test it and report back?

**Comment by TheNewHEROBRINEX** [comment]
Now it's working fine. Compiled without errors.
