### ISSUE TITLE
Add more useful info about bison on macOS

### ISSUE THREAD

**Issue by dktapps** [pmmp/php-build-scripts#152]
To add the homebrew version of bison to PATH, one must consult the instructions provided by `brew info bison`. This may not be an obvious port of call to first-time users building their own binaries.

**Comment by xerenahmed** [comment]
So, what should to do?

**Comment by dktapps** [comment]
There's already an error about bison being too old. It should mention `brew info bison` to find out how PATH should be modified.

Alternatively, the script could just look for homebrew bison and modify the path itself.

**Comment by dktapps** [comment]
Fixed by c5ca8e6918990b8cf4e60bb6e943ff31d457026e.
