### ISSUE TITLE
I can't compile php in Termux.

### ISSUE THREAD

**Issue by middle1** [pmmp/php-build-scripts#167]
I have a phone (with aarch64 processor architecture) and more than one ready-made php did not suit me. I tried to compile it myself, but I got this error at the openssl validation stage. Here is part of the log: "Downloading non-cached file: http://www.openssl.org/source/openssl-3.1.1.tar.gz
2023-06-13 13:35:59 URL:http://www.openssl.org/source/openssl-3.1.1.tar.gz [15544757/15544757] -> "-" [1]
./config: 10: exec: ./Configure: not found". Compiled with this command: "./compile.sh -P5 -j5"

**Comment by dktapps** [comment]
Compiling on Android is not supported.

**Comment by middle1** [comment]
> Compiling on Android is not supported.

It's a pity, but will it ever be possible? On the last version, I could safely use it.

**Comment by dktapps** [comment]
No. We don't recommend running a server on a mobile phone at all.

You can cross-compile a binary using a Linux machine, but this isn't officially supported.

**Comment by middle1** [comment]
> No. We don't recommend running a server on a mobile phone at all.
> 
> You can cross-compile a binary using a Linux machine, but this isn't officially supported.

OK, thanks for the answer.
