### ISSUE TITLE
php/8.2 branch still accessing gmplib.org

### ISSUE THREAD

**Issue by DaisukeDaisuke** [pmmp/php-build-scripts#174]
https://github.com/pmmp/PHP-Binaries/blob/ca8284244cf5f1ef0fe017b5177d6dd5bc9302e1/compile.sh#L535
https://github.com/DaisukeDaisuke/AndroidPHP/actions/runs/5497762460/jobs/10018755749

**Comment by dktapps** [comment]
Fixed by https://github.com/pmmp/PHP-Binaries/commit/5e8752a63f9195b6956600c1f07aa1af77285a8c
