### ISSUE TITLE
Compiling for armv7(not cross-compiling)

### ISSUE THREAD

**Issue by Tarik02** [pmmp/php-build-scripts#19]
I tried to compile php using this for armv7 linux, but it failed like #14. Then i tried to compile using "./compile.sh -t armv7" and it was successful.

**Comment by dktapps** [comment]
how is this worthy of an issue? if you don't specify a target, how does it know what to compile for? Simple logic. Those scripts were not intended for compiling directly on ARM.

**Comment by Tarik02** [comment]
You can detect current target using gcc and C++ directives.

**Comment by dktapps** [comment]
Closing this since we don't support 32-bit targets anymore.
