### ISSUE TITLE
Call to undefined function session_start()

### ISSUE THREAD

**Issue by hypersmc** [pmmp/php-build-scripts#193]
well as the title says it doesn't understand the normal php function session_start();
using version 8.2

**Comment by DaisukeDaisuke** [comment]
The binaries in this repository are cli binaries and are not built to handle web requests, so this feature should not be necessary
Could you please tell us what use case you have in mind?

**Comment by SOF3** [comment]
Please don't use the PM binaries to run web servers. Extensions like pmmpthread will go wrong
.
