### ISSUE TITLE
Exit without outputs

### ISSUE THREAD

**Issue by dadodasyra** [pmmp/php-build-scripts#204]
In order to use #121 I tried to compile myself the lib (since php-debug of releases seems not to contain that gdbinit file).

However the compiler just exits without outputting anything particular. But bin/php7 folders are created (nothing inside)
```
root@bedrock:~/buildphp/PHP-Binaries# ./compile.sh -P5 -d -v
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependencies
[opt] Will compile everything with debugging symbols, will not remove sources
[opt] Will enable valgrind support in PHP
[opt] Compiling with configuration for PocketMine-MP 5
[opt] Selected PHP 8.2.25 (80200)
[WARNING] Only 1 thread is used by default. Increase thread count using -j (e.g. -j 4) to compile faster.
[PHP 8.2.25] downloading...root@bedrock:~/buildphp/PHP-Binaries#
```

**Comment by dktapps** [comment]
Check the install.log file

**Comment by dadodasyra** [comment]
```
root@bedrock:~/buildphp/PHP-Binaries# cat install.log
Wed Dec 18 21:11:56 CET 2024
Linux bedrock 6.8.12-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-2 (2024-09-05T10:03Z) x86_64 GNU/Linux
make is /usr/bin/make
autoconf is /usr/bin/autoconf
automake is /usr/bin/automake
m4 is /usr/bin/m4
getconf is /usr/bin/getconf
gzip is /usr/bin/gzip
bzip2 is /usr/bin/bzip2
bison is /usr/bin/bison
g++ is /usr/bin/g++
git is /usr/bin/git
cmake is /usr/bin/cmake
pkg-config is /usr/bin/pkg-config
re2c is /usr/bin/re2c
wget is /usr/bin/wget
libtool is /usr/bin/libtool
wget is /usr/bin/wget
gcc is /usr/bin/gcc
Cache hit for URL: https://github.com/php/php-src/archive/php-8.2.25.tar.gz

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by dktapps** [comment]
`rm -rf ./download_cache` and run the script again, looks like your cache is corrupted

**Comment by dktapps** [comment]
FWIW you don't need to recompile to get the gdbinit file, you can just grab it from here: https://github.com/php/php-src/blob/master/.gdbinit

**Comment by dadodasyra** [comment]
I've tried. Zbacktrace returns an error about basic functions stuff (which seems to only be present in debug compiles versions).
I will sent it when i get back to my pc

**Comment by dadodasyra** [comment]
'basic_functions_module' has unknown type; cast it to its declared type

**Comment by dadodasyra** [comment]
Got the same error again
Valgrind was missing (seen in install.log)

**Comment by dktapps** [comment]
Not sure what else I can do. The original issue was a cache problem.

**Comment by dadodasyra** [comment]
> Not sure what else I can do. The original issue was a cache problem.

Nope, after the cache cleaning I still had no print of the issue after cleaning cache. The compile script should print/verify the install of Valgrind and/or tells that you can check logs if there's issues

**Comment by dktapps** [comment]
Sure, but that's a different issue. compile.sh has behaved this way for a long time and it's a PITA to change it. 

We could add some logs to make people aware of install.log. Welcome to send a PR if you like.
