### ISSUE TITLE
How to build php 7 for iOS ?

### ISSUE THREAD

**Issue by zxl777** [pmmp/php-build-scripts#25]
Or please tell me how to change the script to compile php for iOS, Thanks.

**Comment by dktapps** [comment]
https://github.com/pmmp/php-build-scripts/blob/master/compile.sh#L259 you can see build targets here.

Sadly nobody in the development team has an iDevice and prepared to test on iOS, so we can't help you with that if you have a problem. The general consensus among the team is that you need to be insane to consider running a server on a phone anyway.
