### ISSUE TITLE
Compiling with simplexml extension

### ISSUE THREAD

**Issue by andris155** [pmmp/php-build-scripts#27]
The MineMarketPE plugin use  `$xml = simplexml_load_file($url);` method, and not work pmmp php files.
How to compile PHP with simplexml extension?

`29.05 00:00:12 [Server] Server thread/CRITICAL Could not execute task MineMarket\ScheduleTask: Call to undefined function MineMarket\simplexml_load_file()`

**Comment by dktapps** [comment]
You can add this to the script yourself if you need it.

**Comment by Pugzy** [comment]
How would one do this, I would also like to enable the XML modules (not sure why they're disabled).
