### ISSUE TITLE
compile.sh is installing PHP 5 instead of PHP7

### ISSUE THREAD

**Issue by madecode15** [pmmp/php-build-scripts#28]
<img width="467" alt="compile" src="https://user-images.githubusercontent.com/25398804/27517980-85b036f8-59a3-11e7-9ded-1ad99711b970.png">

I am not sure why, but after the bin is done compiling and I try to run the server PocketMine says that my PHP version is incorrect (even though the compiler says its downloading PHP7)

**Comment by dktapps** [comment]
do you happen to have a global php5 installation?

**Comment by dktapps** [comment]
Looks to me like you have global php5 installation and it's attempting to use that because compile.sh crashed while compiling your build. Please check the install.log.

**Comment by madecode15** [comment]
@dktapps Yes, I do have a global PHP 5 installation for apache. Should I just remove that before compiling?

**Comment by dktapps** [comment]
> Please check the install.log.

**Comment by madecode15** [comment]
@dktapps Oh misread, it exited with this strange error:


```
virtual memory exhausted: Cannot allocate memory
make: *** [ext/sqlite3/libsqlite/sqlite3.lo] Error 1
```

https://pastebin.com/g72ExXP3

**Comment by madecode15** [comment]
Got it working after removing the global PHP5 installation.. and holy sh*t chunk utils is so fast, my server load no longer spikes up to 30% when new chunks are loaded (only 5% now) >.<. thanks dktapps
