### ISSUE TITLE
installer.sh still points to pocketmine-mp

### ISSUE THREAD

**Issue by alejandroliu** [pmmp/php-build-scripts#3]
Hi,

If using the installer script here, you still get the code from the PocketMine-MP bintray.

I can patch the code in installer.sh to get the latest "phar" from jenkins.  Are you interested in that type of code?

**Comment by dktapps** [comment]
Did you try before [this](https://github.com/pmmp/php-build-scripts/commit/9168b978002467014b6e69fbf2bf75921478fcd9) commit?

**Comment by Intyre** [comment]
Weird....
![Imgur](http://i.imgur.com/tvue9zs.gifv)

**Comment by alejandroliu** [comment]
Sorry, I did my tests before commit 9168b978002467014b6e69fbf2bf75921478fcd9 but posted the issue afterwards.
