### ISSUE TITLE
Compiling for android-aarch64

### ISSUE THREAD

**Issue by tonyboii** [pmmp/php-build-scripts#33]
```
./compile.sh -g -c -x -j 4 -t android-aarch64
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependencies
[opt] Will enable GD2
[opt] Will force compile cURL
[opt] Doing cross-compile
[opt] Set make threads to 4
[opt] Set target to android-aarch64
[INFO] Cross-compiling for Android ARMv8 (aarch64)
[ERROR] Please install "aarch64-linux-musl-gcc"
```

Can someone give me an hint on how to install `aarch64-linux-musl-gcc` ?
I tried googling and after a lot of researches all i found is this: https://github.com/GregorR/musl-cross but i have no idea on how to use it, i don't even know if it's the correct one.

any help is appreciated, thanks :smile:

**Comment by tonyboii** [comment]
I'm running the compile.sh on ubuntu 16.04 LTS 64-bit

**Comment by dktapps** [comment]
You need to compile and install the toolchain using https://github.com/richfelker/musl-cross-make to do this. You need to set target `aarch64-linux-musl` in config.mak.
After that it's a case of `make` and `make install`. You can verify it's working by calling `aarch64-linux-musl-gcc`.

Also note that for Android compilation you must specify the static `-s` flag or the binary will not work correctly.

**Comment by tonyboii** [comment]
Thanks , was easier than expected, it's working fine!

You should insert the toolchain link in the readme or in the error message, the steps to install it are already explained on its readme.

I also had to uncomment `OUTPUT = /usr/local` in **config.mak** not to install it to ./output
