### ISSUE TITLE
Mysql problems with AppVeyor builds

### ISSUE THREAD

**Issue by Driesboy** [pmmp/php-build-scripts#35]
I just downloaded the windows x64 7.2.0 version and MySQL isnt compiled.

**Comment by dktapps** [comment]
MySQL is not required by PocketMine-MP, therefore it is not included. If you need it you can either compile your own, or grab DLLs from a 7.2 package shipped from windows.php.net.

**Comment by Driesboy** [comment]
oh ok thx

Op 3-sep.-2017 11:58 schreef "Dylan K. Taylor" <notifications@github.com>:
