### ISSUE TITLE
I download the bin file at the Jenkins.io but it errors

### ISSUE THREAD

**Issue by Potatoshare88** [pmmp/php-build-scripts#39]
root@ps88:~/pm# sudo ./start.sh
./start.sh: line 54: /root/pm/bin/php7/bin/php: cannot execute binary file: Exec format error
./start.sh: line 54: /root/pm/bin/php7/bin/php: Success
The Bin file's version is php7.2 and OS is Linux(Ubuntu).

(Sorry about my bad English..)

**Comment by dktapps** [comment]
Yoyr system architecture is unsupported. The Jenkins binaries are for x86_64. If you're using arm64 you'll have to compile your own. If you're using any 32-bit platform (x86, armv7, etc) those are no longer supported.

**Comment by Potatoshare88** [comment]
My Os is Ubuntu 64bit. Then I need to change Os to Ubuntu 32bit

**Comment by dktapps** [comment]
Please seek help on https://forums.pmmp.io . This is not an issue with our systems.
