### ISSUE TITLE
SourceForge is very slow | can't compile binaries

### ISSUE THREAD

**Issue by rdstonech** [pmmp/php-build-scripts#46]
When I compile binaries - I'll take error:
_gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now_

It's caused when sh try download libpng. I tried to go to SourseForge - the site is loaded very slowly.
Are there ways to compile the binaries and still leave GD2?

![_2018-02-25_16-38-21](https://user-images.githubusercontent.com/31804440/36642005-54929256-1a4a-11e8-9d93-4cb5d3211a82.png)

**Comment by dktapps** [comment]
Find an alternative download source for LibPNG, or don't enable GD2. This is partly why it's not enabled by default.
