### ISSUE TITLE
installer.sh fails on MacOS Sierra with date error

### ISSUE THREAD

**Issue by mark-zim** [pmmp/php-build-scripts#5]
Running ./installer.sh results in this error.

mini:PocketMine-MP zim$ ./installer.sh
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
[!] Couldn't get the latest PocketMine-MP version

php -v
PHP 7.1.0 (cli) (built: Dec  2 2016 09:19:56) ( NTS )

**Comment by KnownUnown** [comment]
Works perfectly for me @ 8ee66be. OSX, Sierra as well.
![asciicast](https://cloud.githubusercontent.com/assets/3821575/21514625/c3de5d96-cc8c-11e6-823d-940dd2074ddd.gif)

**Comment by robske110** [comment]
I have exactly the same error. Me and Intyre could not figure out why yet. When running it with debug, it looks like it failed to get the information from the server, and therefore breaks the syntax of the date command,. We never figured out why the information is suddenly missing, and what causes it. Bad internet?

**Comment by Humerus** [comment]
This is an issue with the date command version

Please run the following and paste the output:
```sh
shasum -a 256 /bin/date
```

Here is my output (and it works for me):
```sh
➜  ~ shasum -a 256 /bin/date
7cbba457df4c02d6a7fb93046fea0e869732c65a2225bee6f2e8ec290d38c57b  /bin/date
```

Then please run the following:
```sh
date -r $(($(curl "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/api/json?pretty=true&tree=url,artifacts\[fileName\],number,timestamp" | grep -m 1 '"timestamp"' | cut -d ':' -f2- | tr -d ' ",') / 1000))
```
 and:
```sh
date -j -f '%s' $(($(curl "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/api/json?pretty=true&tree=url,artifacts\[fileName\],number,timestamp" | grep -m 1 '"timestamp"' | cut -d ':' -f2- | tr -d ' ",') / 1000))
```

**Comment by mark-zim** [comment]
7cbba457df4c02d6a7fb93046fea0e869732c65a2225bee6f2e8ec290d38c57b  /bin/date

---

mini:bin zim$ date -r $(($(curl "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/api/json?pretty=true&tree=url,artifacts\[fileName\],number,timestamp" | grep -m 1 '"timestamp"' | cut -d ':' -f2- | tr -d ' ",') / 1000))
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-- 100   262    0   262    0     0    724      0 --:--:-- --:--:-- --:--:--   725

---

mini:bin zim$ date -j -f '%s' $(($(curl "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/api/json?pretty=true&tree=url,artifacts\[fileName\],number,timestamp" | grep -m 1 '"timestamp"' | cut -d ':' -f2- | tr -d ' ",') / 1000))
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-- 100   262    0   262    0     0   1174      0 --:--:-- --:--:-- --:--:--  1180

**Comment by mark-zim** [comment]
``` 7cbba457df4c02d6a7fb93046fea0e869732c65a2225bee6f2e8ec290d38c57b  /bin/date ```

``date -r $(($(curl "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/api/json?pretty=true&tree=url,artifacts\[fileName\],number,timestamp" | grep -m 1 '"timestamp"' | cut -d ':' -f2- | tr -d ' ",') / 1000))
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-- 100   262    0   262    0     0    724      0 --:--:-- --:--:-- --:--:--   725 ```

``` date -j -f '%s' $(($(curl "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/api/json?pretty=true&tree=url,artifacts\[fileName\],number,timestamp" | grep -m 1 '"timestamp"' | cut -d ':' -f2- | tr -d ' ",') / 1000))
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-- 100   262    0   262    0     0   1174      0 --:--:-- --:--:-- --:--:--  1180 ```

**Comment by Intyre** [comment]
Works for me..
```
➜  ~ shasum -a 256 /bin/date
7cbba457df4c02d6a7fb93046fea0e869732c65a2225bee6f2e8ec290d38c57b  /bin/date
➜  ~ date -r $(($(curl "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/api/json?pretty=true&tree=url,artifacts\[fileName\],number,timestamp" | grep -m 1 '"timestamp"' | cut -d ':' -f2- | tr -d ' ",') / 1000))
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   262    0   262    0     0    759      0 --:--:-- --:--:-- --:--:--   761
Thu Dec 29 12:35:19 CET 2016
➜  ~ date -j -f '%s' $(($(curl "https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/api/json?pretty=true&tree=url,artifacts\[fileName\],number,timestamp" | grep -m 1 '"timestamp"' | cut -d ':' -f2- | tr -d ' ",') / 1000))
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   262    0   262    0     0    885      0 --:--:-- --:--:-- --:--:--   888
Thu Dec 29 12:35:19 CET 2016
```

**Comment by robske110** [comment]
maybe this is really some sort of firewall/internet provider issue?

**Comment by Humerus** [comment]
It's definitely not a provider issue. I made updates yesterday that I believed should fix the problem. Please try:
```sh
curl -sL https://get.pmmp.io | bash -s -
```
and paste the output

**Comment by robske110** [comment]
Fixed for me, @mark-zim please try again with the latest script.

**Comment by mark-zim** [comment]
``` mini:PocketMine-MP zim$ curl -sL https://get.pmmp.io | bash -s -
bash: line 136: / 1000: syntax error: operand expected (error token is "/ 1000")
[*] Found PocketMine-MP  (build ) using API 
[*] This stable build was released on 
[-] This channel should have a signature, none found
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP  phar... failed!
[!] Couldn't download PocketMine-MP automatically from 
mini:PocketMine-MP zim$ ```

**Comment by mark-zim** [comment]
Nothing before that.

Output of bash -x  ./installer.sh

``` mini:PocketMine-MP zim$ bash -x ./installer.sh
+ CHANNEL=stable
+ BRANCH=master
+ NAME=PocketMine-MP
+ BUILD_URL=
+ LINUX_32_BUILD=PHP_7.0.3_x86_Linux
+ LINUX_64_BUILD=PHP_7.0.3_x86-64_Linux
+ MAC_32_BUILD=PHP_7.0.3_x86_MacOS
+ MAC_64_BUILD=PHP_7.0.3_x86-64_MacOS
+ RPI_BUILD=PHP_7.0.6_ARM_Raspbian_hard
+ ARMV7_BUILD=PHP_7.0.0RC3_ARMv7
+ AND_BUILD=PHP_7.0.0RC3_ARMv7_Android
+ IOS_BUILD=PHP_5.5.13_ARMv6_iOS
+ update=off
+ forcecompile=off
+ alldone=no
+ checkRoot=on
+ XDEBUG=off
+ alternateurl=off
+ INSTALL_DIRECTORY=./
+ IGNORE_CERT=yes
+ getopts rxucid:v:t: opt
+ shopt -s expand_aliases
+ type wget
+ '[' 1 -eq 0 ']'
+ type curl
+ '[' 0 -eq 0 ']'
+ '[' yes == yes ']'
+ alias 'download_file=curl --insecure --silent --location'
+ '[' on == on ']'
++ id -u
+ '[' 501 == 0 ']'
+ '[' stable == soft ']'
+ ENABLE_GPG=no
+ PUBLICKEY_URL=http://cdn.pocketmine.net/pocketmine.asc
+ PUBLICKEY_FINGERPRINT=20D377AFC3F7535B3261AA4DCF48E7E52280B75B
+ PUBLICKEY_LONGID=CF48E7E52280B75B
+ GPG_KEYSERVER=pgp.mit.edu
+ [[ '' != '' ]]
++ curl --insecure --silent --location 'https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/api/json?pretty=true&tree=url,artifacts[fileName],number,timestamp'
+ VERSION_DATA=
++ echo ''
++ grep '"fileName"'
++ cut -d : -f2-
++ tr -d ' ",'
+ FILENAME=
++ echo
++ cut -d _ -f2-
++ cut -d - -f1
+ VERSION=
++ echo ''
++ grep '"number"'
++ cut -d : -f2-
++ tr -d ' ",'
+ BUILD=
++ echo
++ cut -d - -f4-
++ sed -e 's/\.[^.]*$//'
+ API_VERSION=
++ echo ''
++ grep -m 1 '"timestamp"'
++ cut -d : -f2-
++ tr -d ' ",'
./installer.sh: line 136: / 1000: syntax error: operand expected (error token is "/ 1000")
+ echo '[*] Found PocketMine-MP  (build ) using API '
[*] Found PocketMine-MP  (build ) using API 
+ echo '[*] This stable build was released on '
[*] This stable build was released on 
+ '[' no == yes ']'
+ '[' '' == '' ']'
+ [[ stable == \b\e\t\a ]]
+ [[ stable == \s\t\a\b\l\e ]]
+ echo '[-] This channel should have a signature, none found'
[-] This channel should have a signature, none found
+ echo '[*] Installing/updating PocketMine-MP on directory ./'
[*] Installing/updating PocketMine-MP on directory ./
+ mkdir -m 0777 ./
+ cd ./
+ echo '[1/3] Cleaning...'
[1/3] Cleaning...
+ rm -f PocketMine-MP.phar
+ rm -f README.md
+ rm -f CONTRIBUTING.md
+ rm -f LICENSE
+ rm -f start.sh
+ rm -f start.bat
+ rm -f PocketMine-MP.php
+ rm -r -f src/
+ echo -n '[2/3] Downloading PocketMine-MP  phar...'
[2/3] Downloading PocketMine-MP  phar...+ set +e
+ curl --insecure --silent --location ''
+ '[' -s PocketMine-MP.phar ']'
+ rm PocketMine-MP.phar
+ echo ' failed!'
 failed!
+ echo '[!] Couldn'\''t download PocketMine-MP automatically from '
[!] Couldn't download PocketMine-MP automatically from 
+ exit 1
mini:PocketMine-MP zim$  ```

**Comment by Humerus** [comment]
Please try `curl -sL https://get.pmmp.io | bash -s -` again.

**Comment by mark-zim** [comment]
``` mini:PocketMine-MP zim$ curl -sL https://get.pmmp.io | bash -s -
bash: line 136: / 1000: syntax error: operand expected (error token is "/ 1000")
[*] Found PocketMine-MP  (build ) using API 
[*] This stable build was released on 
[-] This channel should have a signature, none found
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP  phar... failed!
[!] Couldn't download PocketMine-MP automatically from 
mini:PocketMine-MP zim$  ```

**Comment by EpicSteve33** [comment]
![screen shot 2017-01-01 at 9 46 08 am](https://cloud.githubusercontent.com/assets/12077835/21582301/34bde20c-d007-11e6-9e7e-62e68c93fe56.png)

when I use `curl -sL https://get.pmmp.io | bash -s -` I get no response, any reason why?

**Comment by robske110** [comment]
Try
`wget -q -O - https://get.pmmp.io | bash -s -`

**Comment by EpicSteve33** [comment]
i'm on mac not linux I have tried that, all I get is command wget not found

**Comment by robske110** [comment]
then install wget using homebrew.
also you could try updating OSX, from your screenshot I can tell your version is ancient

**Comment by robske110** [comment]
oh, and if this needs further discussion please refer to the forums:
https://forums.pmmp.io/forums/help/

**Comment by EpicSteve33** [comment]
i'm on a macbook a1181 I cannot update to a newer mac os

**Comment by EpicSteve33** [comment]
ok

**Comment by dktapps** [comment]
@Humerus Can this issue be closed?
