### ISSUE TITLE
Support for PDO-driver

### ISSUE THREAD

**Issue by jordivantuil** [pmmp/php-build-scripts#52]
We're currently experiencing an issue with MySQL.

As we're planning to create a own plugin that needs database access, PDO is definitely a must.
Without PDO, libraries like Medoo won't work as PDO is required for that.

I know that PMMP is using a binary installation for PHP7.2, is there any possibility to implement or change something so we can get a binary compiled including PDO?

**Comment by JackNoordhuis** [comment]
You can compile the php binaries yourself with pdo and the pdo mysql driver. I created a [gist with a diff and instructions](https://gist.github.com/JackNoordhuis/5c4790a7bfcab7b7dd3d861c713406c3) on how to apply it.
