### ISSUE TITLE
Compile failure in Centos6

### ISSUE THREAD

**Issue by Dkevin2018mc** [pmmp/php-build-scripts#54]
I've tried very many times. The program crashes when PHP checking is executed. I tried to replace the PHP version of php7.2.5, but still can not solve the problem.
[PHP] Downloading additional extensions...
  pthreads: downloading d32079fb4a88e6e008104d36dbbf0
2dd7deb403... done!
  yaml: downloading 2.0.2... done!
  igbinary: downloading 4b61818d361cf2c51472956b4a6e2
be363d681a... done!
  ds: downloading f3989cbfca634256e29f155d6fff77e0e50
5ab8... done!
[PHP] checking...[root@MyServer613 bin]#

**Comment by dktapps** [comment]
please upload the `install.log` file.

**Comment by Dkevin2018mc** [comment]
Sat Apr 28 00:21:22 CST 2018
Linux MyServer613 2.6.32-358.6.1.el6.x86_64 #1 SMP Tue Apr 23 19:29:00 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
make is /usr/bin/make
autoconf is /usr/bin/autoconf
automake is /usr/bin/automake
m4 is /usr/bin/m4
getconf is /usr/bin/getconf
gzip is /bin/gzip
bzip2 is /usr/bin/bzip2
bison is /usr/bin/bison
g++ is /usr/bin/g++
wget is /usr/bin/wget
libtool is /usr/bin/libtool
wget is /usr/bin/wget
gcc is /usr/bin/gcc

**Comment by Dkevin2018mc** [comment]
I have trying again and i will update the install.log when it's exit.thanks

**Comment by Dkevin2018mc** [comment]
`
[install.log](https://github.com/pmmp/php-build-scripts/files/1956931/install.log)
`

**Comment by Dkevin2018mc** [comment]
or http://120.79.227.115/install.log

**Comment by dktapps** [comment]
Your `autoconf` version is out of date.

```
buildconf: autoconf version 2.63 found.
           You need autoconf version 2.64 or newer installed
           to build PHP from Git.
```
