### ISSUE TITLE
Stops compiling for no reason?

### ISSUE THREAD

**Issue by Xelcronia** [pmmp/php-build-scripts#6]
```xel@server1:~$ bash compile.sh
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependecies
[INFO] Compiling for current machine using 64-bit
[PHP] downloading 7.0.13... done!
[zlib] downloading 1.2.8... checking... compiling... installing... cleaning... done!
[mcrypt] downloading 2.5.8... checking... compiling... installing... cleaning... done!
[GMP] downloading 6.1.0... checking... compiling... installing... cleaning... done!
[mbed TLS] downloading 2.2.1... checking... compiling... installing... cleaning... done!
[cURL] downloading curl-7_47_1... checking... compiling... installing... cleaning... done!
[YAML] downloading 0.1.7... checking... compiling... installing... cleaning... done!
[libpng] downloading 1.6.25...
xel@server1:~$
```

I have installed all the dependencies, but it stops.  (Same occurred when I tried 7.0.14)

Running Ubuntu 15.10 64bit

**Comment by jrodr10** [comment]
Same issue... not sure of the cause

**Comment by SalmonGER** [comment]
@jrodr10 edot the libpng version to 1.6.27

**Comment by dktapps** [comment]
why is libpng even included in the build scripts? it's not like PocketMine does any image manipulation. 😕

**Comment by dktapps** [comment]
Could you post your `install.log` from a failed compilation?

**Comment by alex2534alex** [comment]
Compilation failed because of `tar` tried to unpack HTML-page (version/file not founded), which was downloaded instead of archive

**Comment by Xelcronia** [comment]
[install.zip](https://github.com/pmmp/php-build-scripts/files/710553/install.zip)

This install.log?
