### ISSUE TITLE
Failed to install php

### ISSUE THREAD

**Issue by errox404** [pmmp/php-build-scripts#62]
I have install php 7.2.11 on my Linux Debian 8 vserver
`root@robuki:~/server# php -v
PHP 7.2.11-2+0~20181015120510.9+jessie~1.gbp8105e0 (cli) (built: Oct 16 2018 03:39:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.11-2+0~20181015120510.9+jessie~1.gbp8105e0, Copyright (c) 1999-2018, by Zend Technologies`
I use the wget command to download pmmp the install failed 
[https://ibb.co/hmXa3L](url)
[https://ibb.co/hmkHHf](url)
Then I use the php7.2 bin files from pmmp the start.sh from pmmp and the phar 
Then this:
`root@robuki:~/server# ./start.sh
./bin/php7/bin/php: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory`
In your forum I found a help to your compile
[https://forums.pmmp.io/threads/help-with-libmvec-please.5868/](url)
Now I have this problem `root@robuki:~/server# ./compile.sh
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependencies
[INFO] Compiling for current machine using 64-bit
[PHP] downloading 7.2.11... done!
[zlib] downloading 1.2.11... checking... compiling... installing... done!
[GMP] downloading 6.1.2... checking... compiling... installing... done!
[OpenSSL] downloading 1.1.0h... checking... compiling... installing... done!
[cURL] downloading curl-7_61_0... checking... compiling... installing... done!
[YAML] downloading 0.2.1... checking... compiling... installing... done!
[PHP] Downloading additional extensions...
  pthreads: downloading a3057347da7fde81c9ae82ac3669b9c08828c482... done!
  yaml: downloading 2.0.2... done!
  igbinary: downloading 2.0.7... done!
  ds: downloading 35a46a0fba1a0fe2bd4c61f6ea9891d8c4b5e94a...mv: cannot stat 'extension-35a46a0fba1a0fe2bd4c61f6ea9891d8c4b5e94a': No such file or directory`
Can you help me 
Please 😢

**Comment by dktapps** [comment]
This is not a support forum. Please use the [forums](https://forums.pmmp.io) for support.
