### ISSUE TITLE
compile.sh fails on macOS Sierra if -d (xdebug) flag is used

### ISSUE THREAD

**Issue by markkrueg** [pmmp/php-build-scripts#8]
To reproduce:

1) First fix the following as noted in pull request commit c4f111d2bed900f91f58d288e193ef17c02e57d9

-LIBPNG_VERSION="1.6.25"
 +LIBPNG_VERSION="1.6.28"

2) Now the script will run successfully UNLESS you use -d

Last few lines of install.log before it stops:

```
checking whether to enable tokenizer support... yes
checking whether to enable WDDX support... no
checking libexpat dir for WDDX... no
checking enable Weakref suppport... yes
checking whether to enable Xdebug support... yes, shared
checking Check for supported PHP versions... ./configure: line 86365: --version: command not found
configure: error: not supported. Need a PHP version >= 5.5.0 and < 7.2.0 (found )
```

**Comment by dktapps** [comment]
xdebug has to be compiled and installed separately from PHP. The current build scripts don't take this into account.

**Comment by jarne** [comment]
@dktapps I've installed XDebug manually, is it normal that PocketMine completely freezes when setting a breakpoint and resuming it?

**Comment by dktapps** [comment]
7fcedcc56126e01a20d1f5ab93a7738c2c764d7d should fix the issue.
