### ISSUE TITLE
I'm getting error with compile.sh

### ISSUE THREAD

**Issue by dxffety** [pmmp/php-build-scripts#87]
When I use the script, it just dies and gives this log: 

> cp: the target 'Work /php-build-scripts-master/bin/php7 /lib' is not a directory
> Makefile: 307: recipe for target 'install-libs' failed
> make: *** [install-libs] Error 1

How to fix?

**Comment by SOF3** [comment]
The issue tracker is not a help forum. Please use the help channels listed [here](https://github.com/pmmp/PocketMine-MP#discussionhelp).
