### ISSUE TITLE
opcache.so location is hard-coded to build directory

### ISSUE THREAD

**Issue by ZizzyZizzy** [pmmp/php-build-scripts#92]
After building 7.3.16 from the build scripts, the bin folder was moved to an appropriate location locally and on another identical system (OS and Kernel).

It works fine on the local system, but it complains about a missing opcache.so file on the remote system, despite it actually being in the correct place.

```
#bin/php -v

Warning:  Failed loading Zend extension 'opcache.so' (tried: /usr/local/src/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20180731/opcache.so (/usr/local/src/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20180731/opcache.so: cannot open shared object file: No such file or directory), /usr/local/src/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20180731/opcache.so.so /usr/local/src/php-build-scripts/bin/php7/lib/php/extensions/no-debug-zts-20180731/opcache.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

PHP 7.3.16 (cli) (built: Apr 15 2020 11:47:24) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.16, Copyright (c) 1998-2018 Zend Technologies

```

From the same folder:
```
# find . -name opcache.so
./lib/php/extensions/no-debug-zts-20180731/opcache.so

```

The only way to fix this is to update php.ini with the full path to opcache.so.

I would have expected that the extensions folder would be the first place it looks for its own extensions, not the original build folder.

This is new behavior. The last version used, 7.3.9, did not have this issue.

**Comment by dktapps** [comment]
This is not new behaviour, and it's not within our capacity to fix. OPcache was only recently reintroduced to our builds after being absent since 2018.
The path being fixed this way is something we can't do anything about since it comes from somewhere within the PHP build system.

**Comment by ZizzyZizzy** [comment]
Thanks. I didn't realize it was missing for so long.

At least someone else googling the same issue will find this post.
