### ISSUE TITLE
Linux Build #17 fails to load opcache.so

### ISSUE THREAD

**Issue by 95CivicSi** [pmmp/php-build-scripts#98]
When using the Linux php binary from https://jenkins.pmmp.io/job/PHP-7.3-Aggregate/17/artifact/PHP-7.3-Linux-x86_64.tar.gz, an error is given at the beginning of any execution:

```
Warning: Failed loading Zend extension 'opcache.so' (tried: /home/vsts/work/1/s/bin/php7/lib/php/extensions/no-debug-zts-20180731/opcache.so (/home/vsts/work/1/s/bin/php7/lib/php/extensions/no-debug-zts-20180731/opcache.so: cannot open shared object file: No such file or directory), /home/vsts/work/1/s/bin/php7/lib/php/extensions/no-debug-zts-20180731/opcache.so.so (/home/vsts/work/1/s/bin/php7/lib/php/extensions/no-debug-zts-20180731/opcache.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```
This was tested on Ubuntu 18.04 using the `--version` argument.

[error.txt](https://github.com/pmmp/php-build-scripts/files/4841892/error.txt)

**Comment by 95CivicSi** [comment]
This appears to happen on build 15 and 16 as well.

Older copies of php binaries that I have from Jenkins, don't exhibit this problem.  Version output from the working copies I have show this:
```
PHP 7.3.19 (cli) (built: Jun 10 2020 12:28:51) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by JackNoordhuis** [comment]
Seems to be an issue introduced recently, appears to be happening to builds in my docker images. I just use the submodule repo in the PocketMine-MP source repo to build the bin.

https://github.com/JackNoordhuis/PocketMine-Plugins/runs/815558142?check_suite_focus=true
[logs_12.zip](https://github.com/pmmp/php-build-scripts/files/4841987/logs_12.zip)
![Screen Shot 2020-06-28 at 7 13 54 pm](https://user-images.githubusercontent.com/10399774/85943461-9925f280-b973-11ea-80a0-9d058d4a5c5c.png)

**Comment by dktapps** [comment]
This isn't a new issue. https://pmmp.readthedocs.io/en/rtfd/faq/installation/opcache.so.html
