### ISSUE TITLE
Disable math optimisations provided by -ffast-math for SQLite3

### ISSUE THREAD

**Issue by dktapps** [pmmp/php-build-scripts#99]
SQLite3 usually chokes if -ffast-math is provided, but the build script goes out of its way to provide _almost_ all of the flags that would be set if -ffast-math were provided, some of which break SQLite3 at runtime.

The most obvious solution would be to build SQLite3 without -ffast-math on its own, and then enable -ffast-math for everything else.

**Comment by TheNewHEROBRINEX** [comment]
In addition, the flag -ffinite-math-only causes an assertion in SQLite3 to fail at runtime if debugging is enabled.

**Comment by dktapps** [comment]
Versions of SQLite3 3.29 and above don't have this bug. PHP bundles 3.28, so now we build the latest version separately in the compile script. Fixed by 41d61c720131d3200715e34f05d128d0376b7952.
